<?

$sql = "SELECT
		    P.IDPREGUNTA,
		    PR.DESC_PROYECTO,
		    D.DESCRIPCION,
		    REPLACE(REPLACE(P.PREGUNTA, CHR(10), ' '), CHR(13), ' ') AS PREGUNTA,
		    P.RADICADO,
		    CASE
		        WHEN P.IDTIPOPREGUNTA = 1 THEN 'Observación'
		        WHEN P.IDTIPOPREGUNTA = 2 THEN 'Reparo'
		        ELSE 'Sugerencia'
		        END AS TIPOPREGUNTA,
		    R.RADI_FECH_RADI,
		    SD.SGD_DIR_NOMREMDES,
		    M.MUNI_NOMB,
		    CASE
		        WHEN SGD_ATC_TIPO = 0 THEN 'ANONIMO'
		        WHEN SGD_ATC_TIPO = 1 THEN 'Persona Natural'
		        ELSE 'Persona Juridica'
		        END AS SGD_ATC_TIPO
		FROM
		    FLDOC.PC_PREGUNTA P
		INNER JOIN
		    FLDOC.PC_PROYECTO_REGULATORIO PR ON P.IDPROYECTO = PR.IDPROYECTO
		INNER JOIN
		    FLDOC.PC_DOCUMENTOS D ON P.IDDOCUMENTO = D.IDDOCUMENTO
		INNER JOIN
		    FLDOC.RADICADO R ON P.RADICADO = R.RADI_NUME_RADI
		INNER JOIN
		    FLDOC.SGD_DIR_DRECCIONES SD ON SD.RADI_NUME_RADI = R.RADI_NUME_RADI
		LEFT JOIN
		    FLDOC.MUNICIPIO M ON M.ID_PAIS = 170 AND M.DPTO_CODI = SD.DPTO_CODI AND M.MUNI_CODI = SD.MUNI_CODI
		LEFT JOIN
		    FLDOC.SGD_ATC_ATENCION A ON A.SGD_ATC_RADICADO = R.RADI_NUME_RADI
		WHERE P.ESTADOPREGUNTA IS NOT NULL AND 
			  P.IDPROYECTO = $proyecto_id AND 
			  R.RADI_FECH_RADI >= TO_DATE('$fecha_ini', 'YYYY-MM-DD HH24:MI:SS') AND
			  R.RADI_FECH_RADI <= TO_DATE('$fecha_fin', 'YYYY-MM-DD HH24:MI:SS')
		ORDER BY R.RADI_FECH_RADI DESC";
?>