<?

$sql = "SELECT 
			P.IDPREGUNTA, 
			PR.DESC_PROYECTO, 
			D.DESCRIPCION, 
			 REPLACE(REPLACE(P.PREGUNTA, CHR(10), ' '), CHR(13), ' ') AS PREGUNTA, 
			P.RADICADO,
			CASE 
			    WHEN P.IDTIPOPREGUNTA = 1 THEN 'Observación'
		    WHEN P.IDTIPOPREGUNTA = 2 THEN 'Reparo'
		    ELSE 'Sugerencia'
		    END AS TIPOPREGUNTA,
			R.RADI_FECH_RADI,
			SD.SGD_DIR_NOMREMDES,
			M.MUNI_NOMB,
			CASE 
			    WHEN SGD_ATC_TIPO = 0 THEN 'ANONIMO'
			    WHEN SGD_ATC_TIPO = 2 THEN 'Persona Natural'
			    ELSE 'Persona Juridica'
			    END AS SGD_ATC_TIPO,
			SGD_ACT_EDAD,
			CASE
		        WHEN SGD_ATC_COMPONENTE = 1 THEN 'Indígena'
		        WHEN SGD_ATC_COMPONENTE = 2 THEN 'Rrom o gitana'
		        WHEN SGD_ATC_COMPONENTE = 3 THEN 'NARP (negritudes, afrodescendiente, raizal o palenquero)'
		        WHEN SGD_ATC_COMPONENTE = 4 THEN 'Otro'
		        ELSE 'Ninguno'
		    END AS SGD_ATC_COMPONENTE,
		    CASE
		        WHEN SGD_ATC_SEXO = 1 THEN 'Masculino'
		        WHEN SGD_ATC_SEXO = 2 THEN 'Femanino'
		        ELSE 'Otro'
		    END AS SGD_ATC_SEXO,
		    CASE
		        WHEN SGD_ACT_DISCAPACIDAD = 1 THEN 'Si'
		        ELSE 'No'
		    END AS SGD_ACT_DISCAPACIDAD,
		    CASE
		        WHEN SGD_ACT_CONFLICTO = 1 THEN 'Si'
		        ELSE 'No'
		    END AS SGD_ACT_CONFLICTO,
		    CASE
		        WHEN SGD_ACT_LGTBI = 1 THEN 'Si'
		        ELSE 'No'
		    END AS SGD_ACT_LGTBI 
		FROM 
		    FLDOC.PC_PREGUNTA P
		INNER JOIN 
		    FLDOC.PC_PROYECTO_REGULATORIO PR ON P.IDPROYECTO = PR.IDPROYECTO
		INNER JOIN 
		    FLDOC.PC_DOCUMENTOS D ON P.IDDOCUMENTO = D.IDDOCUMENTO
		INNER JOIN 
		    FLDOC.RADICADO R ON P.RADICADO = R.RADI_NUME_RADI
		INNER JOIN 
			FLDOC.SGD_DIR_DRECCIONES SD ON SD.RADI_NUME_RADI = R.RADI_NUME_RADI
		LEFT JOIN 
			FLDOC.MUNICIPIO M ON M.ID_PAIS = 170 AND M.DPTO_CODI = SD.DPTO_CODI AND M.MUNI_CODI = SD.MUNI_CODI
		LEFT JOIN
			FLDOC.SGD_ATC_ATENCION A ON A.SGD_ATC_RADICADO = R.RADI_NUME_RADI
    	WHERE P.ESTADOPREGUNTA IS NOT NULL AND 
			  P.IDPROYECTO = $proyecto_id AND 
			  RADI_FECH_RADI >= TO_DATE('$fecha_ini', 'YYYY-MM-DD HH24:MI:SS') AND
    		  RADI_FECH_RADI <= TO_DATE('$fecha_fin', 'YYYY-MM-DD HH24:MI:SS')
    	ORDER BY R.RADI_FECH_RADI DESC";
?>