<?

$dep = $usuario['dependencia'];
$sql = "SELECT R.RADI_FECH_RADI, R.RADI_DEPE_ACTU, R.RADI_NUME_RADI, R.FECH_VCMTO , R.RA_ASUN, U.USUA_NOMB 
		FROM RADICADO R
		JOIN USUARIO u ON R.RADI_USUA_ACTU = U.USUA_CODI AND R.RADI_DEPE_ACTU = U.DEPE_CODI AND R.FECH_VCMTO IS NOT NULL
		WHERE R.RADI_DEPE_ACTU = $dep AND R.RADI_NUME_RADI LIKE '%2' ORDER BY R.FECH_VCMTO";

?>